### ISSUE TITLE
modId v.0.1.2 produces faulty patch file 

### ISSUE THREAD

**Issue by janitress** [owenmpierce/modId#1]
When using **modId v.01.2** to export/import graphics from **Keen Dreams v.1.13**, it produces a faulty patch file (**kdr.pat**), which messes up the graphics of the game. The patch file looks like this:

`%ext kdr`
`%version 1.4`
`# Load the modified graphics`
`%egahead egahead.kdr`
`%end`

if you comment line two of the patch file (`# %version 1.4`) everything works just fine. so to solve this issue the command for creating that very patch file needs to be changed.

ps.: 
the used batch and def files were those, which come with the download.

pps.:
screenshot: 
![unknown](https://user-images.githubusercontent.com/33704203/48980085-dace2780-f0c4-11e8-8710-df77cccc2643.png)

**Comment by NY00123** [comment]
Finally fixed in v0.1.3 after this whole time.

I think that version 1.4 was originally assumed, due to it being the only version of Keen 4-6 really used for modding with (L)ModKeen and other tools; Or at least Apogee version 1.4 for Keen 4-5, and FormGen version 1.4 for Keen 6.

Additionally, if other patches are already in use for a mod under development, then chances are the .pat file generated by (L)ModKeen isn't even used at all. Thus, it doesn't practically matter what is the %version field value, at least in case the .pat file isn't used.
